// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/messages.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client → Controller
type ClientRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      []byte                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                                                                                    // 32 bytes pubkey
	AfEndpoints   map[string]*AFEndpoint `protobuf:"bytes,2,rep,name=af_endpoints,json=afEndpoints,proto3" json:"af_endpoints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key = af_name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRegister) Reset() {
	*x = ClientRegister{}
	mi := &file_proto_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRegister) ProtoMessage() {}

func (x *ClientRegister) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRegister.ProtoReflect.Descriptor instead.
func (*ClientRegister) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ClientRegister) GetClientId() []byte {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *ClientRegister) GetAfEndpoints() map[string]*AFEndpoint {
	if x != nil {
		return x.AfEndpoints
	}
	return nil
}

type AFEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProbePort     uint32                 `protobuf:"varint,1,opt,name=probe_port,json=probePort,proto3" json:"probe_port,omitempty"`
	VxlanDstPort  uint32                 `protobuf:"varint,2,opt,name=vxlan_dst_port,json=vxlanDstPort,proto3" json:"vxlan_dst_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AFEndpoint) Reset() {
	*x = AFEndpoint{}
	mi := &file_proto_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AFEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AFEndpoint) ProtoMessage() {}

func (x *AFEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AFEndpoint.ProtoReflect.Descriptor instead.
func (*AFEndpoint) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *AFEndpoint) GetProbePort() uint32 {
	if x != nil {
		return x.ProbePort
	}
	return 0
}

func (x *AFEndpoint) GetVxlanDstPort() uint32 {
	if x != nil {
		return x.VxlanDstPort
	}
	return 0
}

// MAC/Neighbor update from Client
type MACUpdate struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Routes []*Type2Route          `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	IsFull bool                   `protobuf:"varint,2,opt,name=is_full,json=isFull,proto3" json:"is_full,omitempty"` // true = full replacement, false = incremental
	// Per-ControllerConn session id and seqid.
	// session_id is regenerated by the client every time it sends is_full=true.
	// seqid starts at 0 with the full sync and increments by 1 per incremental.
	// Used by sync_check daemon to detect lost incremental updates.
	SessionId     string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Seqid         uint64 `protobuf:"varint,4,opt,name=seqid,proto3" json:"seqid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MACUpdate) Reset() {
	*x = MACUpdate{}
	mi := &file_proto_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MACUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MACUpdate) ProtoMessage() {}

func (x *MACUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MACUpdate.ProtoReflect.Descriptor instead.
func (*MACUpdate) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *MACUpdate) GetRoutes() []*Type2Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *MACUpdate) GetIsFull() bool {
	if x != nil {
		return x.IsFull
	}
	return false
}

func (x *MACUpdate) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MACUpdate) GetSeqid() uint64 {
	if x != nil {
		return x.Seqid
	}
	return 0
}

type Type2Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           []byte                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`                            // 6 bytes
	Ip            []byte                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`                              // 4 or 16 bytes
	IsDelete      bool                   `protobuf:"varint,3,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"` // true = withdraw, false = advertise (only meaningful when MACUpdate.is_full=false)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Type2Route) Reset() {
	*x = Type2Route{}
	mi := &file_proto_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type2Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type2Route) ProtoMessage() {}

func (x *Type2Route) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type2Route.ProtoReflect.Descriptor instead.
func (*Type2Route) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Type2Route) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *Type2Route) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *Type2Route) GetIsDelete() bool {
	if x != nil {
		return x.IsDelete
	}
	return false
}

// Controller → Client: full state
type ControllerState struct {
	state                     protoimpl.MessageState      `protogen:"open.v1"`
	ClientCount               uint32                      `protobuf:"varint,1,opt,name=client_count,json=clientCount,proto3" json:"client_count,omitempty"`
	LastClientChangeTimestamp int64                       `protobuf:"varint,2,opt,name=last_client_change_timestamp,json=lastClientChangeTimestamp,proto3" json:"last_client_change_timestamp,omitempty"` // unix nano
	Clients                   map[string]*ClientInfoProto `protobuf:"bytes,3,rep,name=clients,proto3" json:"clients,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key = hex(client_id)
	RouteMatrix               *RouteMatrixProto           `protobuf:"bytes,4,opt,name=route_matrix,json=routeMatrix,proto3" json:"route_matrix,omitempty"`
	RouteTable                []*RouteTableEntryProto     `protobuf:"bytes,5,rep,name=route_table,json=routeTable,proto3" json:"route_table,omitempty"`
	ControllerId              []byte                      `protobuf:"bytes,6,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"` // 32 bytes
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ControllerState) Reset() {
	*x = ControllerState{}
	mi := &file_proto_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerState) ProtoMessage() {}

func (x *ControllerState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerState.ProtoReflect.Descriptor instead.
func (*ControllerState) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ControllerState) GetClientCount() uint32 {
	if x != nil {
		return x.ClientCount
	}
	return 0
}

func (x *ControllerState) GetLastClientChangeTimestamp() int64 {
	if x != nil {
		return x.LastClientChangeTimestamp
	}
	return 0
}

func (x *ControllerState) GetClients() map[string]*ClientInfoProto {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *ControllerState) GetRouteMatrix() *RouteMatrixProto {
	if x != nil {
		return x.RouteMatrix
	}
	return nil
}

func (x *ControllerState) GetRouteTable() []*RouteTableEntryProto {
	if x != nil {
		return x.RouteTable
	}
	return nil
}

func (x *ControllerState) GetControllerId() []byte {
	if x != nil {
		return x.ControllerId
	}
	return nil
}

type ClientInfoProto struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	ClientId       []byte                    `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Endpoints      map[string]*EndpointProto `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key = af_name
	LastSeen       int64                     `protobuf:"varint,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Routes         []*Type2Route             `protobuf:"bytes,4,rep,name=routes,proto3" json:"routes,omitempty"`
	AdditionalCost float64                   `protobuf:"fixed64,5,opt,name=additional_cost,json=additionalCost,proto3" json:"additional_cost,omitempty"` // deprecated, kept for wire compat
	ClientName     string                    `protobuf:"bytes,6,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientInfoProto) Reset() {
	*x = ClientInfoProto{}
	mi := &file_proto_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfoProto) ProtoMessage() {}

func (x *ClientInfoProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfoProto.ProtoReflect.Descriptor instead.
func (*ClientInfoProto) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ClientInfoProto) GetClientId() []byte {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *ClientInfoProto) GetEndpoints() map[string]*EndpointProto {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *ClientInfoProto) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *ClientInfoProto) GetRoutes() []*Type2Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *ClientInfoProto) GetAdditionalCost() float64 {
	if x != nil {
		return x.AdditionalCost
	}
	return 0
}

func (x *ClientInfoProto) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

type EndpointProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            []byte                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"` // 4 or 16 bytes
	ProbePort     uint32                 `protobuf:"varint,2,opt,name=probe_port,json=probePort,proto3" json:"probe_port,omitempty"`
	VxlanDstPort  uint32                 `protobuf:"varint,3,opt,name=vxlan_dst_port,json=vxlanDstPort,proto3" json:"vxlan_dst_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointProto) Reset() {
	*x = EndpointProto{}
	mi := &file_proto_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointProto) ProtoMessage() {}

func (x *EndpointProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointProto.ProtoReflect.Descriptor instead.
func (*EndpointProto) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{6}
}

func (x *EndpointProto) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *EndpointProto) GetProbePort() uint32 {
	if x != nil {
		return x.ProbePort
	}
	return 0
}

func (x *EndpointProto) GetVxlanDstPort() uint32 {
	if x != nil {
		return x.VxlanDstPort
	}
	return 0
}

// Controller → Client: incremental update
type ControllerStateUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*ControllerStateUpdate_ClientJoined
	//	*ControllerStateUpdate_ClientLeft
	//	*ControllerStateUpdate_RouteMatrixUpdate
	//	*ControllerStateUpdate_RouteTableUpdate
	//	*ControllerStateUpdate_ClientInfoUpdate
	Update isControllerStateUpdate_Update `protobuf_oneof:"update"`
	// Optional source-tracking fields. Set when this update was triggered by a
	// MACUpdate from a specific client; the controller echoes the source's
	// session_id+seqid back so the source can confirm its update was processed.
	SourceClientId  []byte `protobuf:"bytes,6,opt,name=source_client_id,json=sourceClientId,proto3" json:"source_client_id,omitempty"`
	SourceSessionId string `protobuf:"bytes,7,opt,name=source_session_id,json=sourceSessionId,proto3" json:"source_session_id,omitempty"`
	SourceSeqid     uint64 `protobuf:"varint,8,opt,name=source_seqid,json=sourceSeqid,proto3" json:"source_seqid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ControllerStateUpdate) Reset() {
	*x = ControllerStateUpdate{}
	mi := &file_proto_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerStateUpdate) ProtoMessage() {}

func (x *ControllerStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerStateUpdate.ProtoReflect.Descriptor instead.
func (*ControllerStateUpdate) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{7}
}

func (x *ControllerStateUpdate) GetUpdate() isControllerStateUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *ControllerStateUpdate) GetClientJoined() *ClientJoined {
	if x != nil {
		if x, ok := x.Update.(*ControllerStateUpdate_ClientJoined); ok {
			return x.ClientJoined
		}
	}
	return nil
}

func (x *ControllerStateUpdate) GetClientLeft() *ClientLeft {
	if x != nil {
		if x, ok := x.Update.(*ControllerStateUpdate_ClientLeft); ok {
			return x.ClientLeft
		}
	}
	return nil
}

func (x *ControllerStateUpdate) GetRouteMatrixUpdate() *RouteMatrixUpdateProto {
	if x != nil {
		if x, ok := x.Update.(*ControllerStateUpdate_RouteMatrixUpdate); ok {
			return x.RouteMatrixUpdate
		}
	}
	return nil
}

func (x *ControllerStateUpdate) GetRouteTableUpdate() *RouteTableUpdateProto {
	if x != nil {
		if x, ok := x.Update.(*ControllerStateUpdate_RouteTableUpdate); ok {
			return x.RouteTableUpdate
		}
	}
	return nil
}

func (x *ControllerStateUpdate) GetClientInfoUpdate() *ClientInfoUpdateProto {
	if x != nil {
		if x, ok := x.Update.(*ControllerStateUpdate_ClientInfoUpdate); ok {
			return x.ClientInfoUpdate
		}
	}
	return nil
}

func (x *ControllerStateUpdate) GetSourceClientId() []byte {
	if x != nil {
		return x.SourceClientId
	}
	return nil
}

func (x *ControllerStateUpdate) GetSourceSessionId() string {
	if x != nil {
		return x.SourceSessionId
	}
	return ""
}

func (x *ControllerStateUpdate) GetSourceSeqid() uint64 {
	if x != nil {
		return x.SourceSeqid
	}
	return 0
}

type isControllerStateUpdate_Update interface {
	isControllerStateUpdate_Update()
}

type ControllerStateUpdate_ClientJoined struct {
	ClientJoined *ClientJoined `protobuf:"bytes,1,opt,name=client_joined,json=clientJoined,proto3,oneof"`
}

type ControllerStateUpdate_ClientLeft struct {
	ClientLeft *ClientLeft `protobuf:"bytes,2,opt,name=client_left,json=clientLeft,proto3,oneof"`
}

type ControllerStateUpdate_RouteMatrixUpdate struct {
	RouteMatrixUpdate *RouteMatrixUpdateProto `protobuf:"bytes,3,opt,name=route_matrix_update,json=routeMatrixUpdate,proto3,oneof"`
}

type ControllerStateUpdate_RouteTableUpdate struct {
	RouteTableUpdate *RouteTableUpdateProto `protobuf:"bytes,4,opt,name=route_table_update,json=routeTableUpdate,proto3,oneof"`
}

type ControllerStateUpdate_ClientInfoUpdate struct {
	ClientInfoUpdate *ClientInfoUpdateProto `protobuf:"bytes,5,opt,name=client_info_update,json=clientInfoUpdate,proto3,oneof"`
}

func (*ControllerStateUpdate_ClientJoined) isControllerStateUpdate_Update() {}

func (*ControllerStateUpdate_ClientLeft) isControllerStateUpdate_Update() {}

func (*ControllerStateUpdate_RouteMatrixUpdate) isControllerStateUpdate_Update() {}

func (*ControllerStateUpdate_RouteTableUpdate) isControllerStateUpdate_Update() {}

func (*ControllerStateUpdate_ClientInfoUpdate) isControllerStateUpdate_Update() {}

type ClientJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientInfo    *ClientInfoProto       `protobuf:"bytes,1,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientJoined) Reset() {
	*x = ClientJoined{}
	mi := &file_proto_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientJoined) ProtoMessage() {}

func (x *ClientJoined) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientJoined.ProtoReflect.Descriptor instead.
func (*ClientJoined) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ClientJoined) GetClientInfo() *ClientInfoProto {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

type ClientLeft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      []byte                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientLeft) Reset() {
	*x = ClientLeft{}
	mi := &file_proto_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientLeft) ProtoMessage() {}

func (x *ClientLeft) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientLeft.ProtoReflect.Descriptor instead.
func (*ClientLeft) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ClientLeft) GetClientId() []byte {
	if x != nil {
		return x.ClientId
	}
	return nil
}

type RouteMatrixUpdateProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteMatrix   *RouteMatrixProto      `protobuf:"bytes,1,opt,name=route_matrix,json=routeMatrix,proto3" json:"route_matrix,omitempty"` // full replacement of route matrix
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteMatrixUpdateProto) Reset() {
	*x = RouteMatrixUpdateProto{}
	mi := &file_proto_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteMatrixUpdateProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteMatrixUpdateProto) ProtoMessage() {}

func (x *RouteMatrixUpdateProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteMatrixUpdateProto.ProtoReflect.Descriptor instead.
func (*RouteMatrixUpdateProto) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{10}
}

func (x *RouteMatrixUpdateProto) GetRouteMatrix() *RouteMatrixProto {
	if x != nil {
		return x.RouteMatrix
	}
	return nil
}

type RouteTableUpdateProto struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Entries       []*RouteTableEntryProto `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"` // full replacement of route table
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteTableUpdateProto) Reset() {
	*x = RouteTableUpdateProto{}
	mi := &file_proto_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTableUpdateProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTableUpdateProto) ProtoMessage() {}

func (x *RouteTableUpdateProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTableUpdateProto.ProtoReflect.Descriptor instead.
func (*RouteTableUpdateProto) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{11}
}

func (x *RouteTableUpdateProto) GetEntries() []*RouteTableEntryProto {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ClientInfoUpdateProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientInfo    *ClientInfoProto       `protobuf:"bytes,1,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientInfoUpdateProto) Reset() {
	*x = ClientInfoUpdateProto{}
	mi := &file_proto_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfoUpdateProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfoUpdateProto) ProtoMessage() {}

func (x *ClientInfoUpdateProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfoUpdateProto.ProtoReflect.Descriptor instead.
func (*ClientInfoUpdateProto) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ClientInfoUpdateProto) GetClientInfo() *ClientInfoProto {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

type RouteMatrixProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entries[i] is row: src_client -> dst_client -> route_entry
	Rows          []*RouteMatrixRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteMatrixProto) Reset() {
	*x = RouteMatrixProto{}
	mi := &file_proto_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteMatrixProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteMatrixProto) ProtoMessage() {}

func (x *RouteMatrixProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteMatrixProto.ProtoReflect.Descriptor instead.
func (*RouteMatrixProto) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{13}
}

func (x *RouteMatrixProto) GetRows() []*RouteMatrixRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type RouteMatrixRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcClientId   []byte                 `protobuf:"bytes,1,opt,name=src_client_id,json=srcClientId,proto3" json:"src_client_id,omitempty"`
	Cells         []*RouteMatrixCell     `protobuf:"bytes,2,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteMatrixRow) Reset() {
	*x = RouteMatrixRow{}
	mi := &file_proto_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteMatrixRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteMatrixRow) ProtoMessage() {}

func (x *RouteMatrixRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteMatrixRow.ProtoReflect.Descriptor instead.
func (*RouteMatrixRow) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{14}
}

func (x *RouteMatrixRow) GetSrcClientId() []byte {
	if x != nil {
		return x.SrcClientId
	}
	return nil
}

func (x *RouteMatrixRow) GetCells() []*RouteMatrixCell {
	if x != nil {
		return x.Cells
	}
	return nil
}

type RouteMatrixCell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DstClientId   []byte                 `protobuf:"bytes,1,opt,name=dst_client_id,json=dstClientId,proto3" json:"dst_client_id,omitempty"`
	NexthopId     []byte                 `protobuf:"bytes,2,opt,name=nexthop_id,json=nexthopId,proto3" json:"nexthop_id,omitempty"`
	AfName        string                 `protobuf:"bytes,3,opt,name=af_name,json=afName,proto3" json:"af_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteMatrixCell) Reset() {
	*x = RouteMatrixCell{}
	mi := &file_proto_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteMatrixCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteMatrixCell) ProtoMessage() {}

func (x *RouteMatrixCell) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteMatrixCell.ProtoReflect.Descriptor instead.
func (*RouteMatrixCell) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{15}
}

func (x *RouteMatrixCell) GetDstClientId() []byte {
	if x != nil {
		return x.DstClientId
	}
	return nil
}

func (x *RouteMatrixCell) GetNexthopId() []byte {
	if x != nil {
		return x.NexthopId
	}
	return nil
}

func (x *RouteMatrixCell) GetAfName() string {
	if x != nil {
		return x.AfName
	}
	return ""
}

type RouteTableEntryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           []byte                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Ip            []byte                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Owners        map[string]int64       `protobuf:"bytes,3,rep,name=owners,proto3" json:"owners,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // key = hex(client_id), value = expire_time unix nano
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteTableEntryProto) Reset() {
	*x = RouteTableEntryProto{}
	mi := &file_proto_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTableEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTableEntryProto) ProtoMessage() {}

func (x *RouteTableEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTableEntryProto.ProtoReflect.Descriptor instead.
func (*RouteTableEntryProto) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{16}
}

func (x *RouteTableEntryProto) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *RouteTableEntryProto) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *RouteTableEntryProto) GetOwners() map[string]int64 {
	if x != nil {
		return x.Owners
	}
	return nil
}

// Controller → Client
type ControllerProbeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProbeId           uint64                 `protobuf:"varint,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	ProbeTimeoutMs    uint32                 `protobuf:"varint,2,opt,name=probe_timeout_ms,json=probeTimeoutMs,proto3" json:"probe_timeout_ms,omitempty"`
	ProbeTimes        uint32                 `protobuf:"varint,3,opt,name=probe_times,json=probeTimes,proto3" json:"probe_times,omitempty"`
	InProbeIntervalMs uint32                 `protobuf:"varint,4,opt,name=in_probe_interval_ms,json=inProbeIntervalMs,proto3" json:"in_probe_interval_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ControllerProbeRequest) Reset() {
	*x = ControllerProbeRequest{}
	mi := &file_proto_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerProbeRequest) ProtoMessage() {}

func (x *ControllerProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerProbeRequest.ProtoReflect.Descriptor instead.
func (*ControllerProbeRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{17}
}

func (x *ControllerProbeRequest) GetProbeId() uint64 {
	if x != nil {
		return x.ProbeId
	}
	return 0
}

func (x *ControllerProbeRequest) GetProbeTimeoutMs() uint32 {
	if x != nil {
		return x.ProbeTimeoutMs
	}
	return 0
}

func (x *ControllerProbeRequest) GetProbeTimes() uint32 {
	if x != nil {
		return x.ProbeTimes
	}
	return 0
}

func (x *ControllerProbeRequest) GetInProbeIntervalMs() uint32 {
	if x != nil {
		return x.InProbeIntervalMs
	}
	return 0
}

// Client → Controller
type ProbeResults struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	ProbeId        uint64                       `protobuf:"varint,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	SourceClientId []byte                       `protobuf:"bytes,2,opt,name=source_client_id,json=sourceClientId,proto3" json:"source_client_id,omitempty"`
	Results        map[string]*ProbeResultEntry `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key = hex(dst_client_id)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProbeResults) Reset() {
	*x = ProbeResults{}
	mi := &file_proto_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResults) ProtoMessage() {}

func (x *ProbeResults) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResults.ProtoReflect.Descriptor instead.
func (*ProbeResults) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{18}
}

func (x *ProbeResults) GetProbeId() uint64 {
	if x != nil {
		return x.ProbeId
	}
	return 0
}

func (x *ProbeResults) GetSourceClientId() []byte {
	if x != nil {
		return x.SourceClientId
	}
	return nil
}

func (x *ProbeResults) GetResults() map[string]*ProbeResultEntry {
	if x != nil {
		return x.Results
	}
	return nil
}

type ProbeResultEntry struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	AfResults     map[string]*AFProbeResult `protobuf:"bytes,1,rep,name=af_results,json=afResults,proto3" json:"af_results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key = af_name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResultEntry) Reset() {
	*x = ProbeResultEntry{}
	mi := &file_proto_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResultEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResultEntry) ProtoMessage() {}

func (x *ProbeResultEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResultEntry.ProtoReflect.Descriptor instead.
func (*ProbeResultEntry) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{19}
}

func (x *ProbeResultEntry) GetAfResults() map[string]*AFProbeResult {
	if x != nil {
		return x.AfResults
	}
	return nil
}

type AFProbeResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LatencyMean    float64                `protobuf:"fixed64,1,opt,name=latency_mean,json=latencyMean,proto3" json:"latency_mean,omitempty"`
	LatencyStd     float64                `protobuf:"fixed64,2,opt,name=latency_std,json=latencyStd,proto3" json:"latency_std,omitempty"`
	PacketLoss     float64                `protobuf:"fixed64,3,opt,name=packet_loss,json=packetLoss,proto3" json:"packet_loss,omitempty"`
	Priority       int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	AdditionalCost float64                `protobuf:"fixed64,5,opt,name=additional_cost,json=additionalCost,proto3" json:"additional_cost,omitempty"` // cost of transiting through this node via this AF
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AFProbeResult) Reset() {
	*x = AFProbeResult{}
	mi := &file_proto_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AFProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AFProbeResult) ProtoMessage() {}

func (x *AFProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AFProbeResult.ProtoReflect.Descriptor instead.
func (*AFProbeResult) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{20}
}

func (x *AFProbeResult) GetLatencyMean() float64 {
	if x != nil {
		return x.LatencyMean
	}
	return 0
}

func (x *AFProbeResult) GetLatencyStd() float64 {
	if x != nil {
		return x.LatencyStd
	}
	return 0
}

func (x *AFProbeResult) GetPacketLoss() float64 {
	if x != nil {
		return x.PacketLoss
	}
	return 0
}

func (x *AFProbeResult) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *AFProbeResult) GetAdditionalCost() float64 {
	if x != nil {
		return x.AdditionalCost
	}
	return 0
}

// Probe channel messages (serialized, then encrypted)
type ProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProbeId       uint64                 `protobuf:"varint,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	SrcTimestamp  int64                  `protobuf:"varint,2,opt,name=src_timestamp,json=srcTimestamp,proto3" json:"src_timestamp,omitempty"` // unix nano
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeRequest) Reset() {
	*x = ProbeRequest{}
	mi := &file_proto_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequest) ProtoMessage() {}

func (x *ProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequest.ProtoReflect.Descriptor instead.
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{21}
}

func (x *ProbeRequest) GetProbeId() uint64 {
	if x != nil {
		return x.ProbeId
	}
	return 0
}

func (x *ProbeRequest) GetSrcTimestamp() int64 {
	if x != nil {
		return x.SrcTimestamp
	}
	return 0
}

type ProbeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProbeId       uint64                 `protobuf:"varint,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	DstTimestamp  int64                  `protobuf:"varint,2,opt,name=dst_timestamp,json=dstTimestamp,proto3" json:"dst_timestamp,omitempty"` // unix nano
	SrcTimestamp  int64                  `protobuf:"varint,3,opt,name=src_timestamp,json=srcTimestamp,proto3" json:"src_timestamp,omitempty"` // echo back sender's src_timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResponse) Reset() {
	*x = ProbeResponse{}
	mi := &file_proto_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResponse) ProtoMessage() {}

func (x *ProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResponse.ProtoReflect.Descriptor instead.
func (*ProbeResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{22}
}

func (x *ProbeResponse) GetProbeId() uint64 {
	if x != nil {
		return x.ProbeId
	}
	return 0
}

func (x *ProbeResponse) GetDstTimestamp() int64 {
	if x != nil {
		return x.DstTimestamp
	}
	return 0
}

func (x *ProbeResponse) GetSrcTimestamp() int64 {
	if x != nil {
		return x.SrcTimestamp
	}
	return 0
}

// Client → Controller: periodic multicast stats
type McastStatsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MacStats      []*MACMcastStats       `protobuf:"bytes,1,rep,name=mac_stats,json=macStats,proto3" json:"mac_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McastStatsReport) Reset() {
	*x = McastStatsReport{}
	mi := &file_proto_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McastStatsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McastStatsReport) ProtoMessage() {}

func (x *McastStatsReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McastStatsReport.ProtoReflect.Descriptor instead.
func (*McastStatsReport) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{23}
}

func (x *McastStatsReport) GetMacStats() []*MACMcastStats {
	if x != nil {
		return x.MacStats
	}
	return nil
}

type MACMcastStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           []byte                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`                                          // 6 bytes src MAC
	TxAccepted    uint64                 `protobuf:"varint,2,opt,name=tx_accepted,json=txAccepted,proto3" json:"tx_accepted,omitempty"`         // outbound accepted
	TxRejected    uint64                 `protobuf:"varint,3,opt,name=tx_rejected,json=txRejected,proto3" json:"tx_rejected,omitempty"`         // outbound rejected (sum of all reasons)
	RxAccepted    uint64                 `protobuf:"varint,4,opt,name=rx_accepted,json=rxAccepted,proto3" json:"rx_accepted,omitempty"`         // inbound accepted
	RxRejected    uint64                 `protobuf:"varint,5,opt,name=rx_rejected,json=rxRejected,proto3" json:"rx_rejected,omitempty"`         // inbound rejected (sum of all reasons)
	RejectReasons []*McastRejectReason   `protobuf:"bytes,6,rep,name=reject_reasons,json=rejectReasons,proto3" json:"reject_reasons,omitempty"` // per-reason breakdown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MACMcastStats) Reset() {
	*x = MACMcastStats{}
	mi := &file_proto_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MACMcastStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MACMcastStats) ProtoMessage() {}

func (x *MACMcastStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MACMcastStats.ProtoReflect.Descriptor instead.
func (*MACMcastStats) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{24}
}

func (x *MACMcastStats) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *MACMcastStats) GetTxAccepted() uint64 {
	if x != nil {
		return x.TxAccepted
	}
	return 0
}

func (x *MACMcastStats) GetTxRejected() uint64 {
	if x != nil {
		return x.TxRejected
	}
	return 0
}

func (x *MACMcastStats) GetRxAccepted() uint64 {
	if x != nil {
		return x.RxAccepted
	}
	return 0
}

func (x *MACMcastStats) GetRxRejected() uint64 {
	if x != nil {
		return x.RxRejected
	}
	return 0
}

func (x *MACMcastStats) GetRejectReasons() []*McastRejectReason {
	if x != nil {
		return x.RejectReasons
	}
	return nil
}

type McastRejectReason struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     string                 `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"` // "tx" or "rx"
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`       // e.g. "rate_limited", "ipv4:udp:5353"
	Count         uint64                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Details       []*McastRejectDetail   `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty"` // per-detail breakdown (deduped)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McastRejectReason) Reset() {
	*x = McastRejectReason{}
	mi := &file_proto_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McastRejectReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McastRejectReason) ProtoMessage() {}

func (x *McastRejectReason) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McastRejectReason.ProtoReflect.Descriptor instead.
func (*McastRejectReason) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{25}
}

func (x *McastRejectReason) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *McastRejectReason) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *McastRejectReason) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *McastRejectReason) GetDetails() []*McastRejectDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

type McastRejectDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        string                 `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"` // e.g. "10.1.0.5 -> 224.0.0.251"
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McastRejectDetail) Reset() {
	*x = McastRejectDetail{}
	mi := &file_proto_messages_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McastRejectDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McastRejectDetail) ProtoMessage() {}

func (x *McastRejectDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McastRejectDetail.ProtoReflect.Descriptor instead.
func (*McastRejectDetail) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{26}
}

func (x *McastRejectDetail) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *McastRejectDetail) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Broadcast relay
type MulticastForward struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceClientId []byte                 `protobuf:"bytes,1,opt,name=source_client_id,json=sourceClientId,proto3" json:"source_client_id,omitempty"`
	Payload        []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // raw ethernet frame
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MulticastForward) Reset() {
	*x = MulticastForward{}
	mi := &file_proto_messages_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MulticastForward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MulticastForward) ProtoMessage() {}

func (x *MulticastForward) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MulticastForward.ProtoReflect.Descriptor instead.
func (*MulticastForward) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{27}
}

func (x *MulticastForward) GetSourceClientId() []byte {
	if x != nil {
		return x.SourceClientId
	}
	return nil
}

func (x *MulticastForward) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MulticastDeliver struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceClientId []byte                 `protobuf:"bytes,1,opt,name=source_client_id,json=sourceClientId,proto3" json:"source_client_id,omitempty"`
	Payload        []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // raw ethernet frame
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MulticastDeliver) Reset() {
	*x = MulticastDeliver{}
	mi := &file_proto_messages_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MulticastDeliver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MulticastDeliver) ProtoMessage() {}

func (x *MulticastDeliver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MulticastDeliver.ProtoReflect.Descriptor instead.
func (*MulticastDeliver) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{28}
}

func (x *MulticastDeliver) GetSourceClientId() []byte {
	if x != nil {
		return x.SourceClientId
	}
	return nil
}

func (x *MulticastDeliver) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_messages_proto protoreflect.FileDescriptor

const file_proto_messages_proto_rawDesc = "" +
	"\n" +
	"\x14proto/messages.proto\x12\x0fvxlancontroller\"\xdf\x01\n" +
	"\x0eClientRegister\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\fR\bclientId\x12S\n" +
	"\faf_endpoints\x18\x02 \x03(\v20.vxlancontroller.ClientRegister.AfEndpointsEntryR\vafEndpoints\x1a[\n" +
	"\x10AfEndpointsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.vxlancontroller.AFEndpointR\x05value:\x028\x01\"Q\n" +
	"\n" +
	"AFEndpoint\x12\x1d\n" +
	"\n" +
	"probe_port\x18\x01 \x01(\rR\tprobePort\x12$\n" +
	"\x0evxlan_dst_port\x18\x02 \x01(\rR\fvxlanDstPort\"\x8e\x01\n" +
	"\tMACUpdate\x123\n" +
	"\x06routes\x18\x01 \x03(\v2\x1b.vxlancontroller.Type2RouteR\x06routes\x12\x17\n" +
	"\ais_full\x18\x02 \x01(\bR\x06isFull\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05seqid\x18\x04 \x01(\x04R\x05seqid\"K\n" +
	"\n" +
	"Type2Route\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\fR\x03mac\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\fR\x02ip\x12\x1b\n" +
	"\tis_delete\x18\x03 \x01(\bR\bisDelete\"\xcf\x03\n" +
	"\x0fControllerState\x12!\n" +
	"\fclient_count\x18\x01 \x01(\rR\vclientCount\x12?\n" +
	"\x1clast_client_change_timestamp\x18\x02 \x01(\x03R\x19lastClientChangeTimestamp\x12G\n" +
	"\aclients\x18\x03 \x03(\v2-.vxlancontroller.ControllerState.ClientsEntryR\aclients\x12D\n" +
	"\froute_matrix\x18\x04 \x01(\v2!.vxlancontroller.RouteMatrixProtoR\vrouteMatrix\x12F\n" +
	"\vroute_table\x18\x05 \x03(\v2%.vxlancontroller.RouteTableEntryProtoR\n" +
	"routeTable\x12#\n" +
	"\rcontroller_id\x18\x06 \x01(\fR\fcontrollerId\x1a\\\n" +
	"\fClientsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .vxlancontroller.ClientInfoProtoR\x05value:\x028\x01\"\xf7\x02\n" +
	"\x0fClientInfoProto\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\fR\bclientId\x12M\n" +
	"\tendpoints\x18\x02 \x03(\v2/.vxlancontroller.ClientInfoProto.EndpointsEntryR\tendpoints\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\x03R\blastSeen\x123\n" +
	"\x06routes\x18\x04 \x03(\v2\x1b.vxlancontroller.Type2RouteR\x06routes\x12'\n" +
	"\x0fadditional_cost\x18\x05 \x01(\x01R\x0eadditionalCost\x12\x1f\n" +
	"\vclient_name\x18\x06 \x01(\tR\n" +
	"clientName\x1a\\\n" +
	"\x0eEndpointsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.vxlancontroller.EndpointProtoR\x05value:\x028\x01\"d\n" +
	"\rEndpointProto\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\x12\x1d\n" +
	"\n" +
	"probe_port\x18\x02 \x01(\rR\tprobePort\x12$\n" +
	"\x0evxlan_dst_port\x18\x03 \x01(\rR\fvxlanDstPort\"\xab\x04\n" +
	"\x15ControllerStateUpdate\x12D\n" +
	"\rclient_joined\x18\x01 \x01(\v2\x1d.vxlancontroller.ClientJoinedH\x00R\fclientJoined\x12>\n" +
	"\vclient_left\x18\x02 \x01(\v2\x1b.vxlancontroller.ClientLeftH\x00R\n" +
	"clientLeft\x12Y\n" +
	"\x13route_matrix_update\x18\x03 \x01(\v2'.vxlancontroller.RouteMatrixUpdateProtoH\x00R\x11routeMatrixUpdate\x12V\n" +
	"\x12route_table_update\x18\x04 \x01(\v2&.vxlancontroller.RouteTableUpdateProtoH\x00R\x10routeTableUpdate\x12V\n" +
	"\x12client_info_update\x18\x05 \x01(\v2&.vxlancontroller.ClientInfoUpdateProtoH\x00R\x10clientInfoUpdate\x12(\n" +
	"\x10source_client_id\x18\x06 \x01(\fR\x0esourceClientId\x12*\n" +
	"\x11source_session_id\x18\a \x01(\tR\x0fsourceSessionId\x12!\n" +
	"\fsource_seqid\x18\b \x01(\x04R\vsourceSeqidB\b\n" +
	"\x06update\"Q\n" +
	"\fClientJoined\x12A\n" +
	"\vclient_info\x18\x01 \x01(\v2 .vxlancontroller.ClientInfoProtoR\n" +
	"clientInfo\")\n" +
	"\n" +
	"ClientLeft\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\fR\bclientId\"^\n" +
	"\x16RouteMatrixUpdateProto\x12D\n" +
	"\froute_matrix\x18\x01 \x01(\v2!.vxlancontroller.RouteMatrixProtoR\vrouteMatrix\"X\n" +
	"\x15RouteTableUpdateProto\x12?\n" +
	"\aentries\x18\x01 \x03(\v2%.vxlancontroller.RouteTableEntryProtoR\aentries\"Z\n" +
	"\x15ClientInfoUpdateProto\x12A\n" +
	"\vclient_info\x18\x01 \x01(\v2 .vxlancontroller.ClientInfoProtoR\n" +
	"clientInfo\"G\n" +
	"\x10RouteMatrixProto\x123\n" +
	"\x04rows\x18\x01 \x03(\v2\x1f.vxlancontroller.RouteMatrixRowR\x04rows\"l\n" +
	"\x0eRouteMatrixRow\x12\"\n" +
	"\rsrc_client_id\x18\x01 \x01(\fR\vsrcClientId\x126\n" +
	"\x05cells\x18\x02 \x03(\v2 .vxlancontroller.RouteMatrixCellR\x05cells\"m\n" +
	"\x0fRouteMatrixCell\x12\"\n" +
	"\rdst_client_id\x18\x01 \x01(\fR\vdstClientId\x12\x1d\n" +
	"\n" +
	"nexthop_id\x18\x02 \x01(\fR\tnexthopId\x12\x17\n" +
	"\aaf_name\x18\x03 \x01(\tR\x06afName\"\xbe\x01\n" +
	"\x14RouteTableEntryProto\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\fR\x03mac\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\fR\x02ip\x12I\n" +
	"\x06owners\x18\x03 \x03(\v21.vxlancontroller.RouteTableEntryProto.OwnersEntryR\x06owners\x1a9\n" +
	"\vOwnersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xaf\x01\n" +
	"\x16ControllerProbeRequest\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\x04R\aprobeId\x12(\n" +
	"\x10probe_timeout_ms\x18\x02 \x01(\rR\x0eprobeTimeoutMs\x12\x1f\n" +
	"\vprobe_times\x18\x03 \x01(\rR\n" +
	"probeTimes\x12/\n" +
	"\x14in_probe_interval_ms\x18\x04 \x01(\rR\x11inProbeIntervalMs\"\xf8\x01\n" +
	"\fProbeResults\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\x04R\aprobeId\x12(\n" +
	"\x10source_client_id\x18\x02 \x01(\fR\x0esourceClientId\x12D\n" +
	"\aresults\x18\x03 \x03(\v2*.vxlancontroller.ProbeResults.ResultsEntryR\aresults\x1a]\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.vxlancontroller.ProbeResultEntryR\x05value:\x028\x01\"\xc1\x01\n" +
	"\x10ProbeResultEntry\x12O\n" +
	"\n" +
	"af_results\x18\x01 \x03(\v20.vxlancontroller.ProbeResultEntry.AfResultsEntryR\tafResults\x1a\\\n" +
	"\x0eAfResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.vxlancontroller.AFProbeResultR\x05value:\x028\x01\"\xb9\x01\n" +
	"\rAFProbeResult\x12!\n" +
	"\flatency_mean\x18\x01 \x01(\x01R\vlatencyMean\x12\x1f\n" +
	"\vlatency_std\x18\x02 \x01(\x01R\n" +
	"latencyStd\x12\x1f\n" +
	"\vpacket_loss\x18\x03 \x01(\x01R\n" +
	"packetLoss\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12'\n" +
	"\x0fadditional_cost\x18\x05 \x01(\x01R\x0eadditionalCost\"N\n" +
	"\fProbeRequest\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\x04R\aprobeId\x12#\n" +
	"\rsrc_timestamp\x18\x02 \x01(\x03R\fsrcTimestamp\"t\n" +
	"\rProbeResponse\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\x04R\aprobeId\x12#\n" +
	"\rdst_timestamp\x18\x02 \x01(\x03R\fdstTimestamp\x12#\n" +
	"\rsrc_timestamp\x18\x03 \x01(\x03R\fsrcTimestamp\"O\n" +
	"\x10McastStatsReport\x12;\n" +
	"\tmac_stats\x18\x01 \x03(\v2\x1e.vxlancontroller.MACMcastStatsR\bmacStats\"\xf0\x01\n" +
	"\rMACMcastStats\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\fR\x03mac\x12\x1f\n" +
	"\vtx_accepted\x18\x02 \x01(\x04R\n" +
	"txAccepted\x12\x1f\n" +
	"\vtx_rejected\x18\x03 \x01(\x04R\n" +
	"txRejected\x12\x1f\n" +
	"\vrx_accepted\x18\x04 \x01(\x04R\n" +
	"rxAccepted\x12\x1f\n" +
	"\vrx_rejected\x18\x05 \x01(\x04R\n" +
	"rxRejected\x12I\n" +
	"\x0ereject_reasons\x18\x06 \x03(\v2\".vxlancontroller.McastRejectReasonR\rrejectReasons\"\x9d\x01\n" +
	"\x11McastRejectReason\x12\x1c\n" +
	"\tdirection\x18\x01 \x01(\tR\tdirection\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\x12<\n" +
	"\adetails\x18\x04 \x03(\v2\".vxlancontroller.McastRejectDetailR\adetails\"A\n" +
	"\x11McastRejectDetail\x12\x16\n" +
	"\x06detail\x18\x01 \x01(\tR\x06detail\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"V\n" +
	"\x10MulticastForward\x12(\n" +
	"\x10source_client_id\x18\x01 \x01(\fR\x0esourceClientId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"V\n" +
	"\x10MulticastDeliver\x12(\n" +
	"\x10source_client_id\x18\x01 \x01(\fR\x0esourceClientId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayloadB\x18Z\x16vxlan-controller/protob\x06proto3"

var (
	file_proto_messages_proto_rawDescOnce sync.Once
	file_proto_messages_proto_rawDescData []byte
)

func file_proto_messages_proto_rawDescGZIP() []byte {
	file_proto_messages_proto_rawDescOnce.Do(func() {
		file_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)))
	})
	return file_proto_messages_proto_rawDescData
}

var file_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_proto_messages_proto_goTypes = []any{
	(*ClientRegister)(nil),         // 0: vxlancontroller.ClientRegister
	(*AFEndpoint)(nil),             // 1: vxlancontroller.AFEndpoint
	(*MACUpdate)(nil),              // 2: vxlancontroller.MACUpdate
	(*Type2Route)(nil),             // 3: vxlancontroller.Type2Route
	(*ControllerState)(nil),        // 4: vxlancontroller.ControllerState
	(*ClientInfoProto)(nil),        // 5: vxlancontroller.ClientInfoProto
	(*EndpointProto)(nil),          // 6: vxlancontroller.EndpointProto
	(*ControllerStateUpdate)(nil),  // 7: vxlancontroller.ControllerStateUpdate
	(*ClientJoined)(nil),           // 8: vxlancontroller.ClientJoined
	(*ClientLeft)(nil),             // 9: vxlancontroller.ClientLeft
	(*RouteMatrixUpdateProto)(nil), // 10: vxlancontroller.RouteMatrixUpdateProto
	(*RouteTableUpdateProto)(nil),  // 11: vxlancontroller.RouteTableUpdateProto
	(*ClientInfoUpdateProto)(nil),  // 12: vxlancontroller.ClientInfoUpdateProto
	(*RouteMatrixProto)(nil),       // 13: vxlancontroller.RouteMatrixProto
	(*RouteMatrixRow)(nil),         // 14: vxlancontroller.RouteMatrixRow
	(*RouteMatrixCell)(nil),        // 15: vxlancontroller.RouteMatrixCell
	(*RouteTableEntryProto)(nil),   // 16: vxlancontroller.RouteTableEntryProto
	(*ControllerProbeRequest)(nil), // 17: vxlancontroller.ControllerProbeRequest
	(*ProbeResults)(nil),           // 18: vxlancontroller.ProbeResults
	(*ProbeResultEntry)(nil),       // 19: vxlancontroller.ProbeResultEntry
	(*AFProbeResult)(nil),          // 20: vxlancontroller.AFProbeResult
	(*ProbeRequest)(nil),           // 21: vxlancontroller.ProbeRequest
	(*ProbeResponse)(nil),          // 22: vxlancontroller.ProbeResponse
	(*McastStatsReport)(nil),       // 23: vxlancontroller.McastStatsReport
	(*MACMcastStats)(nil),          // 24: vxlancontroller.MACMcastStats
	(*McastRejectReason)(nil),      // 25: vxlancontroller.McastRejectReason
	(*McastRejectDetail)(nil),      // 26: vxlancontroller.McastRejectDetail
	(*MulticastForward)(nil),       // 27: vxlancontroller.MulticastForward
	(*MulticastDeliver)(nil),       // 28: vxlancontroller.MulticastDeliver
	nil,                            // 29: vxlancontroller.ClientRegister.AfEndpointsEntry
	nil,                            // 30: vxlancontroller.ControllerState.ClientsEntry
	nil,                            // 31: vxlancontroller.ClientInfoProto.EndpointsEntry
	nil,                            // 32: vxlancontroller.RouteTableEntryProto.OwnersEntry
	nil,                            // 33: vxlancontroller.ProbeResults.ResultsEntry
	nil,                            // 34: vxlancontroller.ProbeResultEntry.AfResultsEntry
}
var file_proto_messages_proto_depIdxs = []int32{
	29, // 0: vxlancontroller.ClientRegister.af_endpoints:type_name -> vxlancontroller.ClientRegister.AfEndpointsEntry
	3,  // 1: vxlancontroller.MACUpdate.routes:type_name -> vxlancontroller.Type2Route
	30, // 2: vxlancontroller.ControllerState.clients:type_name -> vxlancontroller.ControllerState.ClientsEntry
	13, // 3: vxlancontroller.ControllerState.route_matrix:type_name -> vxlancontroller.RouteMatrixProto
	16, // 4: vxlancontroller.ControllerState.route_table:type_name -> vxlancontroller.RouteTableEntryProto
	31, // 5: vxlancontroller.ClientInfoProto.endpoints:type_name -> vxlancontroller.ClientInfoProto.EndpointsEntry
	3,  // 6: vxlancontroller.ClientInfoProto.routes:type_name -> vxlancontroller.Type2Route
	8,  // 7: vxlancontroller.ControllerStateUpdate.client_joined:type_name -> vxlancontroller.ClientJoined
	9,  // 8: vxlancontroller.ControllerStateUpdate.client_left:type_name -> vxlancontroller.ClientLeft
	10, // 9: vxlancontroller.ControllerStateUpdate.route_matrix_update:type_name -> vxlancontroller.RouteMatrixUpdateProto
	11, // 10: vxlancontroller.ControllerStateUpdate.route_table_update:type_name -> vxlancontroller.RouteTableUpdateProto
	12, // 11: vxlancontroller.ControllerStateUpdate.client_info_update:type_name -> vxlancontroller.ClientInfoUpdateProto
	5,  // 12: vxlancontroller.ClientJoined.client_info:type_name -> vxlancontroller.ClientInfoProto
	13, // 13: vxlancontroller.RouteMatrixUpdateProto.route_matrix:type_name -> vxlancontroller.RouteMatrixProto
	16, // 14: vxlancontroller.RouteTableUpdateProto.entries:type_name -> vxlancontroller.RouteTableEntryProto
	5,  // 15: vxlancontroller.ClientInfoUpdateProto.client_info:type_name -> vxlancontroller.ClientInfoProto
	14, // 16: vxlancontroller.RouteMatrixProto.rows:type_name -> vxlancontroller.RouteMatrixRow
	15, // 17: vxlancontroller.RouteMatrixRow.cells:type_name -> vxlancontroller.RouteMatrixCell
	32, // 18: vxlancontroller.RouteTableEntryProto.owners:type_name -> vxlancontroller.RouteTableEntryProto.OwnersEntry
	33, // 19: vxlancontroller.ProbeResults.results:type_name -> vxlancontroller.ProbeResults.ResultsEntry
	34, // 20: vxlancontroller.ProbeResultEntry.af_results:type_name -> vxlancontroller.ProbeResultEntry.AfResultsEntry
	24, // 21: vxlancontroller.McastStatsReport.mac_stats:type_name -> vxlancontroller.MACMcastStats
	25, // 22: vxlancontroller.MACMcastStats.reject_reasons:type_name -> vxlancontroller.McastRejectReason
	26, // 23: vxlancontroller.McastRejectReason.details:type_name -> vxlancontroller.McastRejectDetail
	1,  // 24: vxlancontroller.ClientRegister.AfEndpointsEntry.value:type_name -> vxlancontroller.AFEndpoint
	5,  // 25: vxlancontroller.ControllerState.ClientsEntry.value:type_name -> vxlancontroller.ClientInfoProto
	6,  // 26: vxlancontroller.ClientInfoProto.EndpointsEntry.value:type_name -> vxlancontroller.EndpointProto
	19, // 27: vxlancontroller.ProbeResults.ResultsEntry.value:type_name -> vxlancontroller.ProbeResultEntry
	20, // 28: vxlancontroller.ProbeResultEntry.AfResultsEntry.value:type_name -> vxlancontroller.AFProbeResult
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_proto_messages_proto_init() }
func file_proto_messages_proto_init() {
	if File_proto_messages_proto != nil {
		return
	}
	file_proto_messages_proto_msgTypes[7].OneofWrappers = []any{
		(*ControllerStateUpdate_ClientJoined)(nil),
		(*ControllerStateUpdate_ClientLeft)(nil),
		(*ControllerStateUpdate_RouteMatrixUpdate)(nil),
		(*ControllerStateUpdate_RouteTableUpdate)(nil),
		(*ControllerStateUpdate_ClientInfoUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_messages_proto_goTypes,
		DependencyIndexes: file_proto_messages_proto_depIdxs,
		MessageInfos:      file_proto_messages_proto_msgTypes,
	}.Build()
	File_proto_messages_proto = out.File
	file_proto_messages_proto_goTypes = nil
	file_proto_messages_proto_depIdxs = nil
}
